language: python

python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"

install: 
    - pip install six

script: nosetests -vv

notifications:
    email:
        on_success: change
        on_failure: change
